### ISSUE TITLE
SemanticApprovedRevs point to non-exisent revision

### ISSUE THREAD

**Issue by bawolff** [MWStake/nonwmf-extensions#31]
SemanticApprovedRevs submodule is pointing to b6fc6d3667dcf4cc02f2e7296cd637d343fb58cd but that doesn't seem to exist, which seems to be breaking some tools.

https://github.com/SemanticMediaWiki/SemanticApprovedRevs/tree/b6fc6d3667dcf4cc02f2e7296cd637d343fb58cd gives 404

**Comment by hexmode** [comment]
my bad, thanks for reporting.
