### ISSUE TITLE
Remove extensions that are also in mediawiki-extensions

### ISSUE THREAD

**Issue by samwilson** [MWStake/nonwmf-extensions#38]
The following extensions are listed both here and in https://gerrit.wikimedia.org/g/mediawiki/extensions

Assuming their canonical versions are the Gerrit-hosted ones, they should probably be removed from nonwmf-extensions.

- [ ] ArticleIndex
- [ ] CloneDiff
- [ ] DocBookExport
- [ ] Figures
- [x] GlobalContribs
- [ ] Loops
- [x] MediaWikiAuth
- [ ] PageAuthors
- [x] Shariff-Mediawiki — #39
- [ ] Tabber
- [ ] UserSnoop
- [x] VEForAll — #39
- [x] WikiSEO — #39

**Comment by mary-kate** [comment]
>     * GlobalContribs
Per #36, this was removed already.
>     * MediaWikiAuth
Canonical repo is on GitHub (was previously on WMF gerrit), [SkizNet/mediawiki-MediaWikiAuth](https://github.com/SkizNet/mediawiki-MediaWikiAuth)
>     * Tabber
This was/is a HydraWiki extension, but Wikia/Fandom discontinued HydraWiki around the time they bought Gamepedia from Curse.com and open-sourced the extensions, so I'm not 100% sure now where the canonical repo for this is. At least the old HydraWiki repos on GitLab seem to be abandoned, which (sadly) makes sense, given the facts.
>     * VEForAll
I think this is maintained by Yaron Koren et al. on Gerrit, but might be a good idea to double-check with him regardless.
>     * WikiSEO
Pretty sure @Octfx maintains this on Gerrit, yeah.

**Comment by samwilson** [comment]
Thanks for this, very useful!

>> * GlobalContribs
>
> Per https://github.com/MWStake/nonwmf-extensions/pull/36, this was removed already.

Oops, fixed in extjsonuploader's clone. And I'll work on improving the update process so that it can handle this situation better in future.

> * MediaWikiAuth
>
> Canonical repo is on GitHub (was previously on WMF gerrit), [SkizNet/mediawiki-MediaWikiAuth](https://github.com/SkizNet/mediawiki-MediaWikiAuth)

I've made [T313110](https://phabricator.wikimedia.org/T313110) to track removing this from mediawiki/extensions.

Also just noticed that Shariff is also here as Shariff-Mediawiki; will remove the latter.

**Comment by legoktm** [comment]
I don't think there are any issues in this task, but I would just ask people be cautious when removing extensions from this repository *right now* given that it is being used to determine voter suffrage in the upcoming WMF board election.

**Comment by samwilson** [comment]
Ah, good point! Thanks.

I think the three in #39 are fine. But perhaps others listed above should wait. (There's no hurry with any of this; it's been like this for years I think.)

**Comment by freephile** [comment]
This looks like a straightforward and important task.

**Comment by tgr** [comment]
Per extjsonuploader:
```
Duplicate extension name 'Shariff' detected in these files:
Duplicate extension name 'ArticleIndex' detected in these files:
Duplicate extension name 'CloneDiff' detected in these files:
Duplicate extension name 'DocBookExport' detected in these files:
Duplicate extension name 'Figures' detected in these files:
Duplicate extension name 'HoverGallery' detected in these files:
Duplicate extension name 'Loops' detected in these files:
Duplicate extension name 'MediaWikiAuth' detected in these files:
Duplicate extension name 'PageAuthors' detected in these files:
Duplicate extension name 'Realnames' detected in these files:
Duplicate extension name 'Tabber' detected in these files:
Duplicate extension name 'VEForAll' detected in these files:
Duplicate extension name 'WatchAnalytics' detected in these files:
Duplicate extension name 'WikiSEO' detected in these files:
```
There are three new duplicate entries (HoverGallery, Realnames, WatchAnalytics), plus MediaWikiAuth which is checked in the list but apparently wasn't removed. The others are already listed or a bug in the bot ([T324909](https://phabricator.wikimedia.org/T324909)).

**Comment by kizule** [comment]
I've started giving .gitmodules a cleanup. 😄 

So far, I've made a pull request for sorting it alphabetically: https://github.com/MWStake/nonwmf-extensions/pull/44

After merging that one, I'm going to remove extensions which are marked as read-only or are also in mediawiki-extensions.

**Comment by kizule** [comment]
> I've started giving .gitmodules a cleanup. 😄
> 
> So far, I've made a pull request for sorting it alphabetically: #44
> 
> After merging that one, I'm going to remove extensions which are marked as read-only or are also in mediawiki-extensions.

Waiting now for https://github.com/MWStake/nonwmf-extensions/pull/46 to be merged..
