### ISSUE TITLE
Seperate repository for skins

### ISSUE THREAD

**Issue by legoktm** [MWStake/nonwmf-extensions#5]
I think there's at least one skin in this repository...could/should we have a separate repository for skins? This would at least be useful for codesearch, which has separate search profiles for extensions and skins.

**Comment by hexmode** [comment]
There is at least one.  I've invited you to become a member so you can create a repository.  If you'd rather I do it, I can, but I'm trying to raise the bus factor ;)

**Comment by hexmode** [comment]
There is at least one.  I've invited you to become a member so you can create a repository.  If you'd rather I do it, I can, but I'm trying to raise the bus factor ;)
