### ISSUE TITLE
Should extensions that meet the criteria for archival be removed?

### ISSUE THREAD

**Issue by pppery** [MWStake/nonwmf-extensions#73]
GZWDer created an extension page on MediaWiki.org for every extension in this repo. This made me realize that some of them are abandonware that qualifies for archival, such as https://github.com/Wikifab/PageMediaGallery (still uses the DB_SLAVE constant which was removed in 1.34). Should these things be removed from the repo?

**Comment by pppery** [comment]
There's also repositories that are explicitly marked as archived, i.e KDELogin. Should those be removed?

**Comment by hexmode** [comment]
How would you suggest archiving them? Just deleting?  I'd like to have them still available for future reference, but out of code search.

**Comment by pppery** [comment]
The term "archival" refers to a specific process on MediaWiki.org where the extension page is blanked (but its history is still available), and various other things are done (see https://phabricator.wikimedia.org/maniphest/task/edit/form/33/ for the full list of things that are done when a Gerrit extension is archived).

This repository has not historically been touched by that process. I.e https://www.mediawiki.org/wiki/Extension:Tabber was archived in 2022 and I archived https://www.mediawiki.org/wiki/Extension:PageMediaGallery and https://www.mediawiki.org/wiki/Extension:KDELogin today. All three of those extensions still have pointers in this repo. My question is whether they should. and if something should be done to note that fact.

(For the record, I interact with this repo not because of its use in code search but because MediaWiki.org has a bot that extracts extension.json from every extension here, and uploads it to https://www.mediawiki.org/wiki/Module:ExtensionJson, and then uses it to auto-populate infoboxes. But I am personally fine with whatever - my question is what the intended scope of this repo actually is)

**Comment by hexmode** [comment]
I'm not worried about how these extensions appear on MW.o so archiving them there is fine.  Since this archive is just an list of pointers, I don't think it is necessary to do anything here.

**Comment by pppery** [comment]
OK.

**Comment by samwilson** [comment]
I think at some point it could become useful to remove archived extensions from here, because there's not much point in [ExtJsonUploader](https://extjsonuploader.toolforge.org/) downloading and parsing them. But there aren't all that many I think, so it probably doesn't matter for now.

Whether it's good to keep a list somewhere of archived extensions (other than on mw.o) I'm not sure. Personally the only use I have for archived extensions is to know their names so I don't accidentally re-use one.
